name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: |
          cd app
          npm ci
      - name: Lint
        run: |
          cd app
          npm run lint || echo "Lint errors"
      - name: Build
        run: |
          cd app
          npm run build
      - name: Run tests
        run: |
          cd app
          npm test || echo "No tests yet"
